.server job:
  extends: .subdir job
  image: registry.gitlab.com/lenra/integration/docker-ci-elixir:1.12-alpine
  variables:
    WORKDIR: server
  cache:
    key: server-test_${CI_COMMIT_BRANCH}
    paths:
      - ${WORKDIR}/deps
      - ${WORKDIR}/_build

server build:
  extends: .server job
  stage: build
  script:
    - mix local.hex --force
    - mix deps.get
    - mix compile
  artifacts:
    paths:
      - ${WORKDIR}/deps
      - ${WORKDIR}/_build

# Unit test and code analysis for server
server tests:
  extends:
    - .server job
    - .subdir test job
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_HOST: "postgres"
  stage: test
  coverage: '/\[TOTAL\]  (\d+.\d+)%/'
  script:
    - mix local.hex --force
    - mix deps.get
    - mix credo --strict
    - mix coveralls --umbrella

server dockerize:
  extends:
    - .server job
    - .build docker
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/server
    DOCKER_BUILD_ARGS: "CI CI_JOB_TOKEN"
  before_script:
    - !reference [.docker, before_script]
    - mkdir -p apps/ui_validator/priv/static
    - mv ../json_validator apps/ui_validator/priv/static/json_validator
    - if [[ $(echo $CI_COMMIT_BRANCH | head -c 8) == "release/" ]]; then export DOCKER_BRANCH_IMAGE=${DOCKER_IMAGE}:release-${VERSION}; fi
  needs:
    - job: manage version
      artifacts: true
    - job: server build
      artifacts: true
    - server tests

tag server:
  extends: .tag docker image
  variables:
    DOCKER_STAGING_TAG: release-${VERSION}
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/server
