kind: Deployment
apiVersion: apps/v1
metadata:
  name: lenra-server
  labels:
    k8s-app: lenra-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: lenra-server
  template:
    metadata:
      name: lenra-server
      labels:
        k8s-app: lenra-server
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: lenra-server
          image: "registry.gitlab.com/lenra/platform/lenra_core/server"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
            - name: epmd
              containerPort: 4369
          env:
            - name: PORT
              value: "4000"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: lenra-host
                  key: LENRA_HOST
          envFrom:
            - secretRef:
                name: lenra-server
            - secretRef:
                name: openfaas
            - secretRef:
                name: lenra-postgres
          securityContext:
            privileged: false
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
