name: Populate Release

on:
  release:
    types: [published]

jobs:
  populate_release:
    name: Populate Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: extract_tag
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          echo "Extracting tag..."
          REF="${GITHUB_REF##*/}"
          echo "output.tag=${REF}"
          echo "::set-output name=tag::${REF}"
          if [[ ${GITHUB_REF} == *beta.* ]]; then
            echo "::set-output name=target_ref::beta"
          else
            echo "::set-output name=target_ref::main"
          fi
      - name: create_pr
        uses: lenra-io/create-or-update-pr-action/utils/trigger_workflow@v1.0.0
        with:
          target_ref: ${{ steps.extract_tag.outputs.target_ref }}
          target_repository: "${{ github.repository_owner }}/kubernetes"
          target_workflow: create_or_update_pr.yml
          params: |
            {
              "version": "${{ steps.extract_tag.outputs.tag }}",
              "origin": "server",
              "release_notes": "${{ github.event.release.body }}"
            }
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
